using Base.Test
include("flowcontrol_test.jl")
include("evaluation_test.jl")
include("expressions_test.jl")
include("arithmetic_test.jl")
include("downvalues_test.jl")
include("mxpr_test.jl")
include("orderless_test.jl")
include("patterns_test.jl")
include("simple_expression_test.jl")
