#!/bin/sh

## Load Symata and enter the Symata prompt (REPL) mode
julia --banner=no -i -e "using Symata;@async begin sleep(.1);Symata.RunSymataREPL(Base.active_repl);Symata.transition_to_symata() end"
