#!/bin/sh

## Create a Julia image with Symata precompiled.
## The precompilation statements are generated by the Symata test suite.

## See documentation for PackageCompiler for an explanation of the code below.
## After generating symataimage.so, run the image with
## > julia -J symataimage.so
## You have to call `run_repl()` before entering the repl with the `=` character

#julia --trace-compile=symata_precompile.jl -e "using Symata; Symata.setkerneloptions(:bigint_input, true); Symata.run_testsuite()"

julia --trace-compile=symata_precompile.jl -e "using Symata; Symata.run_testsuite(); Symata.setkerneloptions(:bigint_input, true); Symata.run_testsuite()"

julia -e "using PackageCompiler; PackageCompiler.create_sysimage(:Symata; precompile_statements_file=\"symata_precompile.jl\", sysimage_path=\"symataimage.so\", replace_default=false)"
